import { extractResumePreview, replaceResumeHeadingName } from "./resume-output";

function normalizeResumeText(text: string) {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/\u00a0/g, " ")
    .replace(/[\u2022\u25cf\u25aa]/g, "-")
    .replace(/[\u2013\u2014]/g, "-");
}

function cleanGeneratedPreview(text: string) {
  return text
    .replace(
      /^sure[,!.\s]*here(?:'s| is)\s+the\s+extracted\s+text(?:\s+from\s+the\s+resume)?\s*:\s*/i,
      ""
    )
    .replace(/^here(?:'s| is)\s+the\s+extracted\s+text(?:\s+from\s+the\s+resume)?\s*:\s*/i, "")
    .split("\n")
    .filter((line) => !/\b(?:generated by|zaaa)\b/i.test(line))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function replacePlaceholderNames(text: string, candidateName: string) {
  if (!candidateName) return text;
  return text.replace(/\b(?:john doe|jane doe|candidate name|full name)\b/gi, candidateName);
}

export function extractCandidateNameFromResumeText(text: string) {
  const lines = normalizeResumeText(text)
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  const isNoiseLine = (line: string) =>
    /@/.test(line) ||
    /\b(https?:\/\/|www\.)/i.test(line) ||
    /\b(linkedin|github|portfolio|phone|email|address|location)\b/i.test(line) ||
    /\+?\d[\d\s().-]{6,}\d/.test(line) ||
    /\b(?:here(?:'s| is)\s+the\s+extracted\s+text|sure[,!.\s]*here(?:'s| is)|extracted\s+text\s+from\s+the\s+resume)\b/i.test(
      line
    );

  const cleanLine = (line: string) =>
    line
      .split("|")[0]
      .replace(/\s{2,}/g, " ")
      .trim();

  const candidates = lines.filter((line) => !isNoiseLine(line)).slice(0, 14);

  for (const line of candidates) {
    const cleaned = cleanLine(line);
    const words = cleaned.split(/\s+/).filter(Boolean);
    if (words.length >= 2 && words.length <= 5 && words.every((word) => /^[A-Za-z.'-]+$/.test(word))) {
      return cleaned;
    }
  }

  return cleanLine(candidates[0] ?? "");
}

export function normalizeGeneratedResumePreview(preview: string, sourceResumeText: string) {
  const extracted = cleanGeneratedPreview(extractResumePreview(preview));
  const candidateName = extractCandidateNameFromResumeText(sourceResumeText);
  if (!candidateName) {
    return extracted;
  }

  const withName = replacePlaceholderNames(extracted, candidateName);
  return replaceResumeHeadingName(withName, candidateName);
}
